working for VirtualBox for arm64

diff --git a/packer/build-ce4.sh.in b/packer/build-ce4.sh.in
--- a/packer/build-ce4.sh.in
+++ b/packer/build-ce4.sh.in
@@ -2,16 +2,19 @@
 
 VB_VERSION=$(VBoxManage -V | cut -d. -f1)
 CE4_VERSION="@CE4_VERSION@"
-ARCHITECTURES="amd64"
-for arch in $ARCHITECTURES; do
-    if [ -f ce4-${arch}.json ]; then
-	rm -rf output-virtualbox-iso
-	packer build ce4-${arch}.json 2>&1 | tee build-ce4-${arch}.log
-	if [ -f output-virtualbox-iso/ceenv-${CE4_VERSION}-${arch}.ova ]; then
-	     mv -f output-virtualbox-iso/ceenv-${CE4_VERSION}-${arch}.ova .
-	else
-	    echo "Error: build failed."
-	    exit 127
-	fi
-    fi
-done
+
+ARCHITECTURE=$(uname -m)
+if [ ${ARCHITECTURE} = x86_64 ]; then
+  ARCHITECTURE=amd64
+fi
+
+if [ -f ce4-${ARCHITECTURE}.json ]; then
+  rm -rf output-virtualbox-iso
+  packer build ce4-${ARCHITECTURE}.json 2>&1 | tee build-ce4-${ARCHITECTURE}.log
+  if [ -f output-virtualbox-iso/ceenv-${CE4_VERSION}-${ARCHITECTURE}.ova ]; then
+    mv -f output-virtualbox-iso/ceenv-${CE4_VERSION}-${ARCHITECTURE}.ova .
+  else
+    echo "Error: build failed."
+    exit 127
+  fi
+fi
diff --git a/packer/build-ma4.sh.in b/packer/build-ma4.sh.in
--- a/packer/build-ma4.sh.in
+++ b/packer/build-ma4.sh.in
@@ -2,16 +2,20 @@
 
 VB_VERSION=$(VBoxManage -V | cut -d. -f1)
 MA4_VERSION="@MA4_VERSION@"
-ARCHITECTURES="amd64"
-for arch in $ARCHITECTURES; do
-    if [ -f ma4-${arch}.json ]; then
-	rm -rf output-virtualbox-iso
-	packer build ma4-${arch}.json 2>&1 | tee build-ma4-${arch}.log
-	if [ -f output-virtualbox-iso/MateriAppsLive-${MA4_VERSION}-${arch}.ova ]; then
-	     mv -f output-virtualbox-iso/MateriAppsLive-${MA4_VERSION}-${arch}.ova .
-	else
-	    echo "Error: build failed."
-	    exit 127
-	fi
-    fi
-done
+
+ARCHITECTURE=$(uname -m)
+if [ ${ARCHITECTURE} = x86_64 ]; then
+  ARCHITECTURE=amd64
+fi
+
+if [ -f ma4-${ARCHITECTURE}.json ]; then
+  rm -rf output-virtualbox-iso
+  packer build ma4-${ARCHITECTURE}.json 2>&1 | tee build-ma4-${ARCHITECTURE}.log
+  if [ -f output-virtualbox-iso/MateriAppsLive-${MA4_VERSION}-${ARCHITECTURE}.ova ]; then
+    mv -f output-virtualbox-iso/MateriAppsLive-${MA4_VERSION}-${ARCHITECTURE}.ova .
+  else
+    echo "Error: build failed."
+    exit 127
+  fi
+fi
+d
