update

diff --git a/packer/build-ma3.sh.in b/packer/build-ma3.sh.in
--- a/packer/build-ma3.sh.in
+++ b/packer/build-ma3.sh.in
@@ -4,14 +4,20 @@ VB_VERSION=$(VBoxManage -V | cut -d. -f1)
 MA3_VERSION="@MA3_VERSION@"
 ARCHITECTURES="amd64"
 for arch in $ARCHITECTURES; do
+  check=$(VBoxManage showvminfo MateriAppsLive-${MA3_VERSION}-${arch} > /dev/null 2>&1; echo $?)
+  if [ "${check}" = 0 ]; then
+    echo "Error: MateriAppsLive-${MA3_VERSION}-${arch} exists in VirtualBox."
+    exit 127
+  else
     if [ -f ma3-${arch}.json ]; then
-	rm -rf output-virtualbox-iso
-	packer build ma3-${arch}.json 2>&1 | tee build-ma3-${arch}.log
-	if [ -f output-virtualbox-iso/MateriAppsLive-${MA3_VERSION}-${arch}.ova ]; then
-	     mv -f output-virtualbox-iso/MateriAppsLive-${MA3_VERSION}-${arch}.ova .
-	else
-	    echo "Error: build failed."
-	    exit 127
-	fi
+      rm -rf output-virtualbox-iso
+      packer build ma3-${arch}.json 2>&1 | tee build-ma3-${arch}.log
+      if [ -f output-virtualbox-iso/MateriAppsLive-${MA3_VERSION}-${arch}.ova ]; then
+        mv -f output-virtualbox-iso/MateriAppsLive-${MA3_VERSION}-${arch}.ova .
+      else
+        echo "Error: build failed."
+        exit 127
+      fi
     fi
+  fi
 done
